sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t evilfiend/docker-react -f DockerFile.dev .

script:
  - docker run -e CI=true evilfiend/docker-react npm run test 